#!/usr/bin/python3

import argparse
import os
try:
    import yaml
except Exception:
    print("Please install PyYAML if you want to support yaml configurations!")
    raise
import pprint


def parse_arguments():
    parser = argparse.ArgumentParser(
                      description='Load and print yaml file.',
                      formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('-n', '--new-file', type=str, required=True,
                        help='New yaml file generated by helm')

    args = parser.parse_args()
    return args


def initialize(args):
    f_new = os.path.abspath(args.new_file)
    config =''
    with open(f_new, 'r') as stream:
        try:
            config = yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            print(exc)
    return config
  


def main():
    args = parse_arguments()
    config= initialize(args)
            
    # pprint.pprint(config)
    # print(yaml.dump(config))
    
    bla_fragment = config['pmg_12_2024']
    pprint.pprint(bla_fragment)
    
    for fld in (bla_fragment):
        if fld['value_package'] == 'baseline_automation':
            print  ('\n  BLA key:value pairs \n **************\n' )
            for  key, value in fld.items():
                if 'default' in value:
                    if value['default']:
                        print  ('\n default license  {} : {} \n '.format(value['default'], key))

                print  (' {} : {}'.format(key, value))

if __name__ == "__main__":
    main()
